package classifications;

public enum EuroCarClassification {
	A_MINI, B_SMALL, C_MEDIUM, D_LARGER, E_EXECUTIVE, F_LUXURY, 
	S_SPORT_CABRIOLET_COMPARTMENTS, M_MULTI_PURPOSE_VEHICLE, J_SPORT_UTILITY_VEHICLE
}
